language: node_js
node_js:
  - '0.10'
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start  
  - npm install -g bower grunt-cli
  - bower install
services: mongodb

notifications:
 email:
   - saagar.gugwad@gmail.com
   - mail@sreevisakh.com
   - deepakc8@gmail.com
   - sachinvelaga@gmail.com
   - georgejakes@gmail.com
